openapi: 3.0.0
info:
  title: Documentación de la API REST - Módulo de Autenticación
  description: Detalles de los puntos de acceso para la gestión de usuarios y autenticación.
  version: 1.0.0

# Definición de los servidores donde se encuentra la API
servers:
  - url: http://localhost:3000/api
    description: Servidor de Desarrollo

# Definición de las rutas (endpoints)
paths:
  /auth/login:
    post:
      tags:
        - Autenticación
      summary: Autentica un usuario, devuelve tokens y establece cookies
      description: |-
        Autentica a un usuario con su nombre de usuario y contraseña. Si las credenciales son correctas, devuelve un `accessToken` y establece dos cookies:
        1. `jwt-refresh-token`: Cookie `HttpOnly` para renovar la sesión de forma segura.
        2. `jwt-access-token`: Cookie accesible por el cliente (ej. un servidor Next.js) para gestionar la autenticación.
      requestBody:
        description: Credenciales del usuario para iniciar sesión
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload' # Referencia al esquema definido abajo
            example:
              username: nombre_de_usuario
              password: tu_contraseña
      responses:
        '200':
          description: Inicio de sesión exitoso. Devuelve el accessToken.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
              example:
                accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXJ9...
                message: Inicio de sesión exitoso
        '400':
          description: Campos requeridos faltantes (username o password).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: El username y password son requeridos
        '401':
          description: Credenciales inválidas (username no existe o password incorrecta).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: Credenciales inválidas
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: Error interno del servidor.

  /auth/refresh:
    post:
      tags:
        - Autenticación
      summary: Renueva un accessToken expirado usando el refreshToken
      description: |-
        Renueva un accessToken expirado.
        **Requiere** que la cookie `jwt-refresh-token` (obtenida durante el login) sea enviada en la petición.
        *Nota sobre el Refresh Token: Su único propósito es obtener un nuevo accessToken. No se puede usar para acceder a datos.*
      requestBody:
        # Se indica que no requiere cuerpo de petición, pero se requiere la cookie
        content: {}
      responses:
        '200':
          description: Token refrescado exitosamente. Devuelve un nuevo accessToken.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
              example:
                accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXV9...
                message: Token refrescado exitosamente
        '401':
          description: La cookie refreshToken no fue encontrada en la petición.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: Falta el token de actualización
        '403':
          description: El refreshToken es inválido o ha expirado. El usuario debe volver a iniciar sesión.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: Refresh token inválido o expirado

  /auth/logout:
    post:
      tags:
        - Autenticación
      summary: Cierra la sesión del usuario y elimina las cookies de autenticación
      description: Cierra la sesión del usuario instruyendo al navegador para que elimine las cookies `jwt-refresh-token` y `jwt-access-token`.
      requestBody:
        content: {} # No requiere payload
      responses:
        '200':
          description: Sesión cerrada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Sesión cerrada exitosamente
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: Error interno del servidor.

# Definición de componentes reusables (Esquemas de datos)
components:
  schemas:
    LoginPayload:
      type: object
      properties:
        username:
          type: string
          description: Nombre de usuario para la autenticación.
        password:
          type: string
          description: Contraseña del usuario.
          format: password # Recomendado para indicar que es una contraseña
      required:
        - username
        - password

    LoginSuccess:
      type: object
      properties:
        accessToken:
          type: string
          description: Token de corta duración para acceder a recursos protegidos (JWT).
        message:
          type: string
          description: Mensaje de confirmación.

    ErrorMessage:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error detallado.
